"""add_brand_objectives

Revision ID: 09694bdcb7b8
Revises: a6d046e08cb8
Create Date: 2026-06-19 22:39:12.769582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09694bdcb7b8'
down_revision: Union[str, Sequence[str], None] = 'a6d046e08cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_objectives',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('objective', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_objectives_brand_id'), 'brand_objectives', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_objectives_tenant_id'), 'brand_objectives', ['tenant_id'], unique=False)

    # Enable PostgreSQL Row-Level Security (RLS)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TABLE brand_objectives ENABLE ROW LEVEL SECURITY;")
        op.execute("ALTER TABLE brand_objectives FORCE ROW LEVEL SECURITY;")
        op.execute("DROP POLICY IF EXISTS tenant_isolation ON brand_objectives;")
        op.execute("""
            CREATE POLICY tenant_isolation ON brand_objectives
              USING (tenant_id = current_setting('app.current_tenant_id', true));
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP POLICY IF EXISTS tenant_isolation ON brand_objectives;")
        op.execute("ALTER TABLE brand_objectives DISABLE ROW LEVEL SECURITY;")

    op.drop_index(op.f('ix_brand_objectives_tenant_id'), table_name='brand_objectives')
    op.drop_index(op.f('ix_brand_objectives_brand_id'), table_name='brand_objectives')
    op.drop_table('brand_objectives')
    # ### end Alembic commands ###
