"""fix_outbox_tenant_id

Revision ID: 0c06f3a7b210
Revises: 9c00afc7ba94
Create Date: 2026-06-18 11:30:42.046546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c06f3a7b210'
down_revision: Union[str, Sequence[str], None] = '9c00afc7ba94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox', sa.Column('tenant_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox', 'tenant_id')
    # ### end Alembic commands ###
