"""add_tenant_cascade_and_suspension

Revision ID: 47d59327789e
Revises: 09694bdcb7b8
Create Date: 2026-06-20 05:49:44.801434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d59327789e'
down_revision: Union[str, Sequence[str], None] = '09694bdcb7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_approvals_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_audit_events_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('brand_objectives', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_brand_objectives_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('brand_properties', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_brand_properties_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    naming_convention = {
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }
    with op.batch_alter_table('brands', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_brands_tenant_id_tenants', type_='foreignkey')
        batch_op.create_foreign_key('fk_brands_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('cadences', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_cadences_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_campaigns_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('circuit_breakers', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_circuit_breakers_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_connections_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('consent_bases', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_consent_bases_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('cost_ledger', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_cost_ledger_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('fulfillment_costs', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_fulfillment_costs_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('op_dependencies', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_op_dependencies_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('op_traces', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_op_traces_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('ops', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_ops_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_order_lines_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_orders_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_outbox_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_policy_versions_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_refunds_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('shadow_decisions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_shadow_decisions_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('spend_facts', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_spend_facts_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('touchpoints', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_touchpoints_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('trust_events', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_trust_events_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('trust_snapshots', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_trust_snapshots_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'is_active')
    with op.batch_alter_table('trust_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trust_snapshots_tenant_id', type_='foreignkey')
    with op.batch_alter_table('trust_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trust_events_tenant_id', type_='foreignkey')
    with op.batch_alter_table('touchpoints', schema=None) as batch_op:
        batch_op.drop_constraint('fk_touchpoints_tenant_id', type_='foreignkey')
    with op.batch_alter_table('spend_facts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_spend_facts_tenant_id', type_='foreignkey')
    with op.batch_alter_table('shadow_decisions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_shadow_decisions_tenant_id', type_='foreignkey')
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_constraint('fk_refunds_tenant_id', type_='foreignkey')
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_policy_versions_tenant_id', type_='foreignkey')
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_constraint('fk_outbox_tenant_id', type_='foreignkey')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_tenant_id', type_='foreignkey')
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_lines_tenant_id', type_='foreignkey')
    with op.batch_alter_table('ops', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ops_tenant_id', type_='foreignkey')
    with op.batch_alter_table('op_traces', schema=None) as batch_op:
        batch_op.drop_constraint('fk_op_traces_tenant_id', type_='foreignkey')
    with op.batch_alter_table('op_dependencies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_op_dependencies_tenant_id', type_='foreignkey')
    with op.batch_alter_table('fulfillment_costs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fulfillment_costs_tenant_id', type_='foreignkey')
    with op.batch_alter_table('cost_ledger', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cost_ledger_tenant_id', type_='foreignkey')
    with op.batch_alter_table('consent_bases', schema=None) as batch_op:
        batch_op.drop_constraint('fk_consent_bases_tenant_id', type_='foreignkey')
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_connections_tenant_id', type_='foreignkey')
    with op.batch_alter_table('circuit_breakers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_circuit_breakers_tenant_id', type_='foreignkey')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_constraint('fk_campaigns_tenant_id', type_='foreignkey')
    with op.batch_alter_table('cadences', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cadences_tenant_id', type_='foreignkey')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_constraint('fk_brands_tenant_id', type_='foreignkey')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_brands_tenant_id', 'tenants', ['tenant_id'], ['id'])
    with op.batch_alter_table('brand_properties', schema=None) as batch_op:
        batch_op.drop_constraint('fk_brand_properties_tenant_id', type_='foreignkey')
    with op.batch_alter_table('brand_objectives', schema=None) as batch_op:
        batch_op.drop_constraint('fk_brand_objectives_tenant_id', type_='foreignkey')
    with op.batch_alter_table('brand_objectives', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_brand_objectives_tenant_id', 'tenants', ['tenant_id'], ['id'])
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_events_tenant_id', type_='foreignkey')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_approvals_tenant_id', type_='foreignkey')
    # ### end Alembic commands ###
