"""initial_schema

Revision ID: 88fb80ecf5ab
Revises: 
Create Date: 2026-06-15 08:14:04.198068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88fb80ecf5ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('op_id', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('surface', sa.String(length=24), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_op_id'), 'approvals', ['op_id'], unique=False)
    op.create_index(op.f('ix_approvals_tenant_id'), 'approvals', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('op_id', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_audit_events_op_id'), 'audit_events', ['op_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_brand_id'), 'campaigns', ['brand_id'], unique=False)
    op.create_index(op.f('ix_campaigns_tenant_id'), 'campaigns', ['tenant_id'], unique=False)
    op.create_table('circuit_breakers',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('tripped_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id', 'brand_id', 'domain')
    )
    op.create_table('connections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_brand_id'), 'connections', ['brand_id'], unique=False)
    op.create_index(op.f('ix_connections_tenant_id'), 'connections', ['tenant_id'], unique=False)
    op.create_table('cost_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('op_id', sa.String(length=32), nullable=True),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_ledger_op_id'), 'cost_ledger', ['op_id'], unique=False)
    op.create_index(op.f('ix_cost_ledger_tenant_id'), 'cost_ledger', ['tenant_id'], unique=False)
    op.create_table('op_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('op_id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_op_traces_op_id'), 'op_traces', ['op_id'], unique=False)
    op.create_index(op.f('ix_op_traces_tenant_id'), 'op_traces', ['tenant_id'], unique=False)
    op.create_table('ops',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('reversibility', sa.String(length=16), nullable=False),
    sa.Column('statutory', sa.Boolean(), nullable=False),
    sa.Column('cost_amount_minor', sa.Integer(), nullable=True),
    sa.Column('cost_currency', sa.String(length=8), nullable=True),
    sa.Column('preview_summary', sa.Text(), nullable=True),
    sa.Column('parent_op_id', sa.String(length=32), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('idem_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idem_key')
    )
    op.create_index(op.f('ix_ops_brand_id'), 'ops', ['brand_id'], unique=False)
    op.create_index(op.f('ix_ops_state'), 'ops', ['state'], unique=False)
    op.create_index(op.f('ix_ops_tenant_id'), 'ops', ['tenant_id'], unique=False)
    op.create_index('ix_ops_tenant_state', 'ops', ['tenant_id', 'state'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('attributed_campaign_id', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_attributed_campaign_id'), 'orders', ['attributed_campaign_id'], unique=False)
    op.create_index(op.f('ix_orders_brand_id'), 'orders', ['brand_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('op_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('op_id')
    )
    op.create_index(op.f('ix_outbox_status'), 'outbox', ['status'], unique=False)
    op.create_table('policy_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rules_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_versions_tenant_id'), 'policy_versions', ['tenant_id'], unique=False)
    op.create_table('processed_webhook_messages',
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hosting_tier', sa.String(length=16), nullable=False),
    sa.Column('gcp_project', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('touchpoints',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_touchpoints_campaign_id'), 'touchpoints', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_touchpoints_customer_id'), 'touchpoints', ['customer_id'], unique=False)
    op.create_index(op.f('ix_touchpoints_tenant_id'), 'touchpoints', ['tenant_id'], unique=False)
    op.create_table('trust_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('base_delta', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_events_brand_id'), 'trust_events', ['brand_id'], unique=False)
    op.create_index(op.f('ix_trust_events_tenant_id'), 'trust_events', ['tenant_id'], unique=False)
    op.create_table('trust_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_snapshots_brand_id'), 'trust_snapshots', ['brand_id'], unique=False)
    op.create_index(op.f('ix_trust_snapshots_tenant_id'), 'trust_snapshots', ['tenant_id'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_tenant_id'), 'brands', ['tenant_id'], unique=False)
    op.create_table('fulfillment_costs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('shipping_cost_minor', sa.Integer(), nullable=False),
    sa.Column('marketplace_fee_minor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulfillment_costs_order_id'), 'fulfillment_costs', ['order_id'], unique=False)
    op.create_index(op.f('ix_fulfillment_costs_tenant_id'), 'fulfillment_costs', ['tenant_id'], unique=False)
    op.create_table('op_dependencies',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('parent_op_id', sa.String(length=32), nullable=False),
    sa.Column('from_op_id', sa.String(length=32), nullable=False),
    sa.Column('to_op_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['from_op_id'], ['ops.id'], ),
    sa.ForeignKeyConstraint(['parent_op_id'], ['ops.id'], ),
    sa.ForeignKeyConstraint(['to_op_id'], ['ops.id'], ),
    sa.PrimaryKeyConstraint('parent_op_id', 'from_op_id', 'to_op_id')
    )
    op.create_index(op.f('ix_op_dependencies_tenant_id'), 'op_dependencies', ['tenant_id'], unique=False)
    op.create_table('order_lines',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('unit_price_minor', sa.Integer(), nullable=False),
    sa.Column('line_discount_minor', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_cost_minor', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_lines_order_id'), 'order_lines', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_lines_tenant_id'), 'order_lines', ['tenant_id'], unique=False)
    op.create_table('spend_facts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spend_facts_campaign_id'), 'spend_facts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_spend_facts_tenant_id'), 'spend_facts', ['tenant_id'], unique=False)
    op.create_table('brand_properties',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('connection_ref', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_properties_brand_id'), 'brand_properties', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_properties_tenant_id'), 'brand_properties', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_brand_properties_type'), 'brand_properties', ['type'], unique=False)
    op.create_table('cadences',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('schedule', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=False),
    sa.Column('last_finding_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cadences_brand_id'), 'cadences', ['brand_id'], unique=False)
    op.create_index(op.f('ix_cadences_tenant_id'), 'cadences', ['tenant_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('order_line_id', sa.String(length=32), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_order_line_id'), 'refunds', ['order_line_id'], unique=False)
    op.create_index(op.f('ix_refunds_tenant_id'), 'refunds', ['tenant_id'], unique=False)

    # Enable Row-Level Security (RLS) on Postgres
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # Enable RLS on tenants
        op.execute("ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;")
        op.execute("ALTER TABLE tenants FORCE ROW LEVEL SECURITY;")
        op.execute("DROP POLICY IF EXISTS tenant_isolation ON tenants;")
        op.execute("""
            CREATE POLICY tenant_isolation ON tenants
              USING (id = current_setting('app.current_tenant_id', true));
        """)

        tables_with_tenant = [
            "brands", "ops", "audit_events", "trust_events",
            "trust_snapshots", "cost_ledger", "connections",
            "brand_properties", "cadences", "op_traces", "approvals",
            "orders", "order_lines", "refunds", "fulfillment_costs",
            "campaigns", "spend_facts", "touchpoints", "circuit_breakers",
            "op_dependencies", "policy_versions"
        ]

        for table in tables_with_tenant:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
            op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table};")
            op.execute(f"""
                CREATE POLICY tenant_isolation ON {table}
                  USING (tenant_id = current_setting('app.current_tenant_id', true));
            """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_tenant_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_order_line_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_cadences_tenant_id'), table_name='cadences')
    op.drop_index(op.f('ix_cadences_brand_id'), table_name='cadences')
    op.drop_table('cadences')
    op.drop_index(op.f('ix_brand_properties_type'), table_name='brand_properties')
    op.drop_index(op.f('ix_brand_properties_tenant_id'), table_name='brand_properties')
    op.drop_index(op.f('ix_brand_properties_brand_id'), table_name='brand_properties')
    op.drop_table('brand_properties')
    op.drop_index(op.f('ix_spend_facts_tenant_id'), table_name='spend_facts')
    op.drop_index(op.f('ix_spend_facts_campaign_id'), table_name='spend_facts')
    op.drop_table('spend_facts')
    op.drop_index(op.f('ix_order_lines_tenant_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_order_id'), table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index(op.f('ix_op_dependencies_tenant_id'), table_name='op_dependencies')
    op.drop_table('op_dependencies')
    op.drop_index(op.f('ix_fulfillment_costs_tenant_id'), table_name='fulfillment_costs')
    op.drop_index(op.f('ix_fulfillment_costs_order_id'), table_name='fulfillment_costs')
    op.drop_table('fulfillment_costs')
    op.drop_index(op.f('ix_brands_tenant_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_trust_snapshots_tenant_id'), table_name='trust_snapshots')
    op.drop_index(op.f('ix_trust_snapshots_brand_id'), table_name='trust_snapshots')
    op.drop_table('trust_snapshots')
    op.drop_index(op.f('ix_trust_events_tenant_id'), table_name='trust_events')
    op.drop_index(op.f('ix_trust_events_brand_id'), table_name='trust_events')
    op.drop_table('trust_events')
    op.drop_index(op.f('ix_touchpoints_tenant_id'), table_name='touchpoints')
    op.drop_index(op.f('ix_touchpoints_customer_id'), table_name='touchpoints')
    op.drop_index(op.f('ix_touchpoints_campaign_id'), table_name='touchpoints')
    op.drop_table('touchpoints')
    op.drop_table('tenants')
    op.drop_table('processed_webhook_messages')
    op.drop_index(op.f('ix_policy_versions_tenant_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_outbox_status'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_brand_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_attributed_campaign_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_ops_tenant_state', table_name='ops')
    op.drop_index(op.f('ix_ops_tenant_id'), table_name='ops')
    op.drop_index(op.f('ix_ops_state'), table_name='ops')
    op.drop_index(op.f('ix_ops_brand_id'), table_name='ops')
    op.drop_table('ops')
    op.drop_index(op.f('ix_op_traces_tenant_id'), table_name='op_traces')
    op.drop_index(op.f('ix_op_traces_op_id'), table_name='op_traces')
    op.drop_table('op_traces')
    op.drop_index(op.f('ix_cost_ledger_tenant_id'), table_name='cost_ledger')
    op.drop_index(op.f('ix_cost_ledger_op_id'), table_name='cost_ledger')
    op.drop_table('cost_ledger')
    op.drop_index(op.f('ix_connections_tenant_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_brand_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_table('circuit_breakers')
    op.drop_index(op.f('ix_campaigns_tenant_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_brand_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_op_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_approvals_tenant_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_op_id'), table_name='approvals')
    op.drop_table('approvals')

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP POLICY IF EXISTS tenant_isolation ON tenants;")
        op.execute("ALTER TABLE tenants DISABLE ROW LEVEL SECURITY;")

        tables_with_tenant = [
            "brands", "ops", "audit_events", "trust_events",
            "trust_snapshots", "cost_ledger", "connections",
            "brand_properties", "cadences", "op_traces", "approvals",
            "orders", "order_lines", "refunds", "fulfillment_costs",
            "campaigns", "spend_facts", "touchpoints", "circuit_breakers",
            "op_dependencies", "policy_versions"
        ]

        for table in tables_with_tenant:
            op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table};")
            op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")
    # ### end Alembic commands ###
