"""update policy_versions table structure

Revision ID: 9c00afc7ba94
Revises: 89123f070704
Create Date: 2026-06-15 17:58:23.676379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '9c00afc7ba94'
down_revision: Union[str, Sequence[str], None] = '89123f070704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_versions', sa.Column('status', sa.String(length=16), server_default='active', nullable=False))
    # Rename rules_json to params to preserve data
    op.alter_column('policy_versions', 'rules_json', new_column_name='params', existing_type=sa.JSON())
    op.add_column('policy_versions', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('policy_versions', sa.Column('created_by', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_versions', 'created_by')
    op.drop_column('policy_versions', 'note')
    op.alter_column('policy_versions', 'params', new_column_name='rules_json', existing_type=sa.JSON())
    op.drop_column('policy_versions', 'status')
    # ### end Alembic commands ###
