import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { TenantProvider } from "@/contexts/TenantContext";
import { QueryProvider } from "@/providers/QueryProvider";
import { DevGate } from "@/components/DevGate";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-zinc-950 text-zinc-50 font-sans">
        <TenantProvider>
          <QueryProvider>
            <DevGate>
              {children}
            </DevGate>
          </QueryProvider>
        </TenantProvider>
      </body>
    </html>
  );
}
